### ISSUE TITLE
includes is not a function

### ISSUE THREAD

**Issue by aykutyaman** [team-jwd/cold-brew#58]
When I run sample tests a get this error:
```
ColdBrew client should be able to do a Google search:
     TypeError: ["click","sendKeys"].includes is not a function
      at validNavigation (node_modules/cold-brew/src/cold-brew-test.js:365:34)
      at node_modules/cold-brew/src/cold-brew-test.js:334:7
      at Array.every (native)
      at thenableWebDriverProxy.client.do (node_modules/cold-brew/src/cold-brew-test.js:333:41)
      at Context.<anonymous> (cold-brew-test.js:23:5)
```
I am on Ubuntu 15.10
Chrome Version 55.0.2883.87 (64 bit)
If we change [this line](https://github.com/team-jwd/cold-brew/blob/master/src/cold-brew-test.js#L364) as this it works:
``` (['click', 'sendKeys'].indexOf(navigationEvent[0]) > -1);```

If it is ok, I would do a pull request.

**Comment by wcbarnes** [comment]
I changed it
